parameters:
    applications:
        mapbender_mobile:
            title: Mobile demo
            screenshot: screenshot.png
            description: Simple application using mobile template
            published: true
            template:  'Mapbender\MobileBundle\Template\Mobile'
            layersets:
                main:
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml
                        version: 1.3.0
                        layers:
                            10: { name: Mapbender_User,    title : User, visible: true, legendurl: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mapbender_User&format=image/png&STYLE=default }
                            22: { name: Mapbender_Names,   title : Name, visible: true, queryable: true}
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 100
                        isBaseSource: false
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            30: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 100
                        isBaseSource: true
                    osm_2:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo (with Opacity)
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            30: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: false
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 30
                        isBaseSource: true
            elements:
                footer:
                    # buttons parameters: action,activate,deactivate are ignored for elements at mobilePane
                    layertree-button:
                        title: Themes
                        tooltip: Themes
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        icon: iconLayertree
                        target: layertree

                    bss-button:
                        title: mb.core.basesourceswitcher.class.title
                        tooltip: mb.core.basesourceswitcher.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconLegend
                        label: false
                        target: basesourceswitcher

                    gps-button:
                        class: Mapbender\CoreBundle\Element\GpsPosition
                        label: false
                        target: map
                        icon: iconGps
                        average: '1'
                        follow: false
                        centerOnFirstPosition: true
                        zoomToAccuracyOnFirstPosition: true

                    imprint-button:
                        title: Imprint
                        tooltip: Imprint
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        icon: iconInfoActive
                        target: imprint

                    help-button:
                        title: mb.core.aboutdialog.tag.help
                        tooltip: mb.core.aboutdialog.tag.help
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        icon: iconHelp
                        target: help

                    about-mapbender-button:
                        title: mb.core.aboutdialog.tag.about
                        tooltip: mb.core.aboutdialog.tag.about
                        class: Mapbender\CoreBundle\Element\Button
                        label: false
                        icon: iconAbout
                        target: html-about-mapbender
                    shareUrl:
                        class: Mapbender\CoreBundle\Element\ShareUrl
                        label: false
                content:
                    map:
                        class: Mapbender\CoreBundle\Element\Map
                        layersets: [main]
                        srs: EPSG:25832
                        extents:
                            start: [361000,5619000,371150,5625000]
                            max: [-500000,4350000,1600000,6850000]
                        scales: [5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                        otherSrs: ["EPSG:25833","EPSG:31466","EPSG:31467","EPSG:3857","EPSG:4326"]
                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        components: ["rotation", "zoom_in_out", "zoom_max"]
                        anchor: left-top
                        draggable: false

                mobilePane:
                    layertree:
                        title: Themes
                        class: Mapbender\CoreBundle\Element\Layertree
                        target: map
                        type: element
                        autoOpen: false
                        showBaseSource: false
                        menu: []

                    featureinfo:
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        target: map
                        deactivateOnClose: false
                        autoActivate: true
                        printResult: false
                        displayType: tabs
                        onlyValid: true

                    imprint:
                        title: Imprint
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: '<div style="color: #6FB536; font-weight:bold" >powered by Mapbender. Read more about Mapbender at the <a href="https://www.mapbender.org" target="_blank">Mapbender Project Page</a>.</div>'
                        classes: html-element-inline

                    help:
                        title: mb.core.aboutdialog.tag.help
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: 'Enjoy the new Mapbender mobile Template. Please note that not all elements can be used in the mobile application. <div style="color: #6FB536; font-weight:bold">Find out more about the Mapbender mobile in the <a href="https://doc.mapbender.org/en/customization/mapbender_templates.html" target="_blank">Template Documentation</a>.</div>'
                        classes: html-element-inline

                    basesourceswitcher:
                        tooltip: mb.core.basesourceswitcher.class.title
                        class: Mapbender\CoreBundle\Element\BaseSourceSwitcher
                        target: map
                        instancesets:
                            is1:
                                title: "OSM Demo (with opacity)"
                                group: ~
                                instances: [osm_2]
                            is2:
                                title: "OSM Demo"
                                group: ~
                                instances: [osm]

                    html-about-mapbender:
                        title: mb.core.aboutdialog.tag.about
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        classes: html-element-inline
                        content: "<p>Mapbender is an OSGeo Project. Find out more about OSGeo at <br/><a href=\"https://www.osgeo.org\" target=\"_blank\">https://www.osgeo.org</a><br/><a href=\"https://www.osgeo.org/projects/mapbender/\" target=\"_blank\">https://www.osgeo.org/projects/mapbender/</a></p>"
